### ISSUE TITLE
Nextion HMI read longed

### ISSUE THREAD

**Issue by Fiiti** [ITEAD-Thierry/NextionX#1]
I can't wait to read the next part to this library. Then hopefully with the longed for Read function.
So please excuse me for using this issue to send this wish.
I very much appreciate your experience and implementation. 
Regards Fii

**Comment by ITEAD-Thierry** [comment]
Hi @Fiiti, thanks for your positive feedback!
Yesterday, I wanted to publish a new Blog article on the Nextion.tech Sunday blog and release the next version of this NextionX library. Unfortunately, I didn't yet get round a few OOP forward declaring issues and I didn't want to publish half-baked stuff with potential problems. Victim of my own perfectionism, we'll have probably to wait until next Sunday to see the version 0.7.0 (we will jump over the 0.6.0 which spoiled my last weekend) with
- a more consistent and simplified API
- less memory consumption with more functionality
- handling of the Nextion return codes, especially the error and status codes in the Debug version
- attachable onPress() and onRelease() functions for each component to handle TouchPress and TouchRelease events.

I hope that when you see it, you'll say that it was worth waiting one more week.

**Comment by ITEAD-Thierry** [comment]
New version v0.7.0 is published!
