### ISSUE TITLE
send variables to the function when called

### ISSUE THREAD

**Issue by oliroon** [ITEAD-Thierry/NextionX#4]
Hi,
I want to be able to send a variable when I call the function when a button action is triggered.
In your example you use:

 momButton.setOnRelease(LED_off);

This calls the function "LED_off" with no variable and no end brackets.
my example is this where I send a variable to the function to make my code more streamlined

 RdecButton.setOnRelease(Manual_Button_op(8));
I have about 8 of these.

I have looked at the NextionX.h file and see that the "()" looks like it is included when the code reads the line. I remove these but still cant get the code to function .The error is "invalid use of void expression".

Hope you can help.

**Comment by ITEAD-Thierry** [comment]
Looking at the code of NextionX.h, you’ll see that when you call .setOnRelease() or .setOnTouch(), these methods expect a function pointer of the type void* function(void), which takes no parameters as the simplest form of a generic callback function and which is qualified by the function name without brackets. 
Accepting universal parameter(s) (byte, int, word, char*, String, how much ?) would result in the need for multiple overloaded methods and different function types in the internal listener list which would bloat the library code probably beyond an Arduino UNO’s storage. Remember, in opposite to other programming languages, C/C++ does not allow dynamic types, which means that for each type, and void *func(void), void *func(byte), void *func(int) are all different types, the corresponding handlers and storage have to be explicitly present at compile time.
So, this does not seem to be the way to go on small embedded systems with limited flash memory.
But there is a simple workaround for your specific request:
Just write 8 small function wrappers like
```
void cb0() {myFunc(0);}
void cb1() {myFunc(1);}
```
… and so on.
Then, you can attach these with
```
b0.setOnRelease(cb0);
b1.setOnRelease(cb1);
```
… and so on and you are done.

**Comment by oliroon** [comment]
Thank you. that will work.
