### ISSUE TITLE
how to adress Objects on other pages

### ISSUE THREAD

**Issue by Fiiti** [ITEAD-Thierry/NextionX#8]
Hi Thierry,

I wonder how can I adress an local Object on different Pages.
e.g. myNex.cmdWrite("LED1.pic=6");   works with one page.

But if I using more than one page, the object is not known.
It doesn't matter, if I set the vscope to global or local.

Any hint for me?
![image](https://user-images.githubusercontent.com/25975978/108879670-c78ec700-7601-11eb-91c0-3dcda0acb805.png)

Of course i can use:

NexComm myNex;
NexComp ir_led(myNex, 6, 4);   /Page 6, ID 4
ir_led.setAttr("pic", 6)

But I hoped, that there is a direct way without using al little amount of mem from the mcu.

Regards
Fii

**Comment by ITEAD-Thierry** [comment]
Either with full addressing, i.e. `myNex.cmdWrite("page6.LED1.pic=6");` as documented in the Nextion Instruction Set on the nextion.tech website (such basics should not be discussed here...), or you declare the component as `NexComp LED1p6(myNex,6,4);` and then use `LED1p2.setAttr("pic",6);`.
Global or local says only if the component can be addressed either always (if global and with full addressing) or only if the containing page is loaded and the current page (if local). But this is also  documented in the Nextion Editor Guide on the nextion.tech website...

**Comment by Fiiti** [comment]
Thank you. Case can closed.
