### ISSUE TITLE
Code Refactoring

### ISSUE THREAD

**Issue by sstaub** [ITEAD-Thierry/NextionX#9]
Thanks for the inspiring library and the Blog. I found many things in the code which might done better, so I worked on it.
Better variable names, Doxygen style documentation, functions which can deleted, and deleting most of the this-> stuff which is not needed ...
I tried to separate the `.h` file into a `.h` and a `.cpp` file but with no luck, it seems this a problem with templates I have to investigate.
Feel free to overtake (some) changes.
The refactored lib is attached, with an example for Mega.
[NextionX.zip](https://github.com/ITEAD-Thierry/NextionX/files/6071058/NextionX.zip)

**Comment by ITEAD-Thierry** [comment]
Thank you very much for that! I looked quickly over your variant - it looks promising. You created doxygen tags for methods which are only temporarily public in this interim release but which are intended to be protected or private in later releases. That’s why in my manual documentation, some are intentionally not mentioned. I have in the meantime added (but not yet fully tested and thus not yet published) a bunch of new functions to read attributes back from Nextion components into the MCU, asynchronously (not blocking), so I can consider your optimizations only at a later moment. 
Although I admire everything which is made better as my code, we have to respect the multi-platform compatibility, everything has to compile in C++11 (for Arduino), C++14 (for Teensy), and C++17 (for ESP). So, testing and integrating your mods might come only in a few weeks.
Template parameters require always that declarations and definitions are in the same .h file.

**Comment by sstaub** [comment]
Debug works, I renamed most of the functions and variables. e.g. using _var is old C style, also Set and Get methods are no more needed when using overloading functions. I wrote the very popular Ticker library which works on all platforms. The problem I see is using the Arduino String library which is a problem for microcontrollers with small RAM, cause of defragmentation of the heap.
With non blocking did you mean interrupt based? Receiving data from the Nextion display with RX interrupts will solve many timing problems.

**Comment by sstaub** [comment]
GitHub have now a discussion forum which can activated in settings. It is better for non issues problems and ideas.

**Comment by ITEAD-Thierry** [comment]
With non blocking, I mean launching another custom callback function of a NexComp when the requested answer has fully arrived.
I’m aware of the fact that many things can be done in a more modern style, but Arduino users, especially beginners, seem to feel more comfortable with familiar naming conventions and the good old getSomething, setSomething, writeSomething and readSomething methods.
